### ISSUE TITLE
Image generation is not working

### ISSUE THREAD

**Issue by DenkingOfficial** [xrpgame/xyz_plot_script#2]
It just not working for some reason

Video demonstration:

[screencast-192.168.0.66_7860-2022.10.17-18_53_43.webm](https://user-images.githubusercontent.com/38957619/196196078-47165051-2e4c-45df-a929-2d6a02a0bf5b.webm)

As you can see all fields are filled with values, but it isn't work

No any logs in console, it doesn's starting

**Comment by zer0TF** [comment]
~~Usually there is some output in the console telling you if something went wrong? Is there *really nothing*?~~

~~If I had to guess, it doesn't like your list of hypernetworks (i.e. one of them is not named/spelled correctly). Are you sure that these are valid hypernetworks?~~

~~Try swapping out hypernetworks for some other parameter (like Seed or Sampler) and see if that works? If it works, you know it's the hypernetwork list.~~

~~I'll leave this open for now, there may be a bug here, not sure.~~

See below.

**Comment by zer0TF** [comment]
Nevermind - the latest WebUI fixed an issue where Steps was missing from the possible values to choose from, so this script was thrown off.

I just pushed a fix, please try the latest version and let me know if it works: https://github.com/xrpgame/xyz_plot_script/blob/master/xyz_grid.py

**Comment by zer0TF** [comment]
Closing - please reopen an issue if you are still experiencing errors! 🙂
