### ISSUE TITLE
error on new webui update

### ISSUE THREAD

**Issue by IkariDevGIT** [xrpgame/xyz_plot_script#8]
`Error loading script: xyz_grid.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "D:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "D:\stable-diffusion-webui\scripts\xyz_grid.py", line 17, in <module>
    from modules.processing import StableDiffusionProcessingTxt2Img, process_images, get_correct_sampler
ImportError: cannot import name 'get_correct_sampler' from 'modules.processing' (D:\stable-diffusion-webui\modules\processing.py)`

**Comment by RURon** [comment]
I just created a pull request to make it working again...
https://github.com/xrpgame/xyz_plot_script/pull/9

**Comment by zer0TF** [comment]
Oops, sorry @RURon, I fixed it without seeing your PR.

Commit https://github.com/xrpgame/xyz_plot_script/commit/45db5dab7e56d0505289353f4c09620b3c7a88d2 resolves this issue.
